version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: expenses-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - expenses-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
        - DATABASE=${DATABASE}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - JWT_SECRET=${JWT_SECRET}
        - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
        - EMAIL_HOST=${EMAIL_HOST}
        - EMAIL_PORT=${EMAIL_PORT}
        - EMAIL_ADDRESS=${EMAIL_ADDRESS}
        - EMAIL_FROM=${EMAIL_FROM}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        - EMAIL_TO=${EMAIL_TO}
        - COMPANY_NAME=${COMPANY_NAME}
    container_name: expenses-app
    ports:
      - "6010:6010"
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - expenses-network
    depends_on:
      - redis

  notifications-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifications-worker
    command: npm run worker:notifications:prod
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    restart: unless-stopped
    networks:
      - expenses-network
    depends_on:
      - redis

networks:
  expenses-network:
    driver: bridge
