version: "3.8"

services:
  williams-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
        - DATABASE=${DATABASE}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - JWT_SECRET=${JWT_SECRET}
        - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
        - EMAIL_HOST=${EMAIL_HOST}
        - EMAIL_PORT=${EMAIL_PORT}
        - EMAIL_ADDRESS=${EMAIL_ADDRESS}
        - EMAIL_FROM=${EMAIL_FROM}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        - EMAIL_TO=${EMAIL_TO}
        - COMPANY_NAME=${COMPANY_NAME}
    container_name: expenses-app
    ports:
      - "6010:6010"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - expenses-network

networks:
  expenses-network:
    driver: bridge
